openapi: 3.0.0
info:
  title: "Balance and Movements of a Deposit Account"
  description: "Reto Capa de gestion equipo 12"
  version: 1.0.0
servers:
  - url: 'https://VisualStudioDoc....'

tags:
  - name: "DEPOSITS  Cuentas de depositos"
    description: "Saldos y Movimientos de una cuenta"

paths:
  #################################################################################
  #  Balance And Movements of Account
  #################################################################################
  /balanceandmovements:
    post:
      security:
        - bearerAuth: []
      tags:
        - "BalanceAndMovements"
      summary: "Saldos y Movimientos de cuentas de Depositos"
      description: "Presenta informacion del saldo y movimientos de una cuenta"
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
            example: "application/json"
          description: "Cabecera para indicar que el contenido a negociar es Json"
          required: true

      requestBody:
        required: true
        description: "Cuerpo de la petición"
        content:
          application/vnd.bancolombia.v2+json:
            schema:
              $ref: '#/components/schemas/balanceAndMovementsRequest'

      responses:
        200:
          description: "TRANSACCIÓN EXITOSA"
          content:
            application/vnd.bancolombia.v2+json:
              schema:
                $ref: "#/components/schemas/balanceAndMovementsResponse"

        default:
          description: "Mensaje de error por defecto"
          content:
            application/vnd.bancolombia.v2+json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    $ref: "#/components/schemas/Error"

#################################################################################
# COMPONENTS
#################################################################################
components:
  securitySchemes:
    bearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"

  #################################################################################
  # SCHEMES
  #################################################################################
  schemas:

  #################################################################################
  # Scheme BALANCE AND MOVEMENTS REQUEST
  #################################################################################
    balanceAndMovementsRequest:
      type: "object"
      required:
        - data
      properties:
        data:
          type: "array"
          uniqueItems: true
          items:
            type: "object"
            required:
              - "requestInformation"
            properties:
              categoryRequestInformation:
                $ref: "#/components/schemas/requestInformation"

  #################################################################################
  # Scheme BALANCE AND MOVEMENTS RESPONSE
  #################################################################################
    balanceAndMovementsResponse:
      type: object
      required:
        - data
        - status
      properties:
        data:
          type: "array"
          uniqueItems: true
          items:
            type: "object"
            required:
              - "balanceInformation"
              - "transactionsInformation"
            properties:
              balanceInformation:
                $ref: "#/components/schemas/balanceInformation"
              transactionsInformation:
                $ref: "#/components/schemas/transactionsInformation"
        status:
          $ref: "#/components/schemas/status"
  #################################################################################
  # Scheme BALANCE INFORMATION FOR RESPONSE
  #################################################################################

    balanceInformation:
      type: "object"
      required:
        - available
        - moreRecords
        - officeCode
      properties:
        available:
          type: "string"
          description: "Saldo disponible"
          example: "150000000"
          maxLength: 20
        unavailableClearing:
          type: "string"
          description: "Saldo en Canje"
          example: "15000000"
          maxLength: 20
        pockets:
          type: "string"
          description: "Saldo en bolsillos"
          example: "20000000"
          maxLength: 20

  #################################################################################
  # Scheme TRANSACTIONS INFORMATION FOR RESPONSE
  #################################################################################

    transactionsInformation:
      type: "object"
      required:
        - responsSize
        - moreRecords
        - office
        - customer
        - transaction
      properties:
        responseSize:
          type: "string"
          description: "Total de registros"
          example: "30"
          maxLength: 2
        moreRecords:
          type: "string"
          description: "Indicador de existencia de más registros"
          example: "true"
        office:
          type: "object"
          description: "Código de la oficina donde se realizó la transacción o de la oficina dueña de la cuenta a la que pertenece la transacción"
          properties:
            officeInformation:
              $ref: "#/components/schemas/officeInformation"
        relatedTransferAccount:
          type: "object"
          description: "Información de la cuenta relacionada, solo para transferencias."
          properties:
            relatedTransferAccountInformation:
              $ref: "#/components/schemas/relatedTransferAccountInformation"
        customer:
          type: "object"
          description: "Información del cliente dueño de la cuenta destino cuando el movimiento fue transferencia"
          properties:
            customerInformation:
              $ref: "#/components/schemas/customerInformation"
        transaction:
          type: "array"
          description: "Lista de movimientos"
          items:
            properties:
              movementsInformation:
                $ref: "#/components/schemas/movementsInformation"

  #################################################################################
  # Scheme INFORMATION FOR REQUEST
  #################################################################################
    requestInformation:
      type: "object"
      required:
        - accountType
        - accountNumber
        - paginationKey
      properties:
        accountType:
          type: "string"
          description: "Tipo de cuenta"
          example: "CUENTA_DE_AHORRO"
        accountNumber:
          type: "string"
          description: "Número de la cuenta"
          maxLength: 16
          example: "01530951240"
        paginationSize:
          type: "string"
          description: "Cantidad de registros por página"
          maxLength: 2
          example: "30"
        paginationKey:
          type: "string"
          description: "Número de página"
          maxLength: 3
          example: "1"
        transactionStartDate:
          type: "string"
          description: "Fecha inicio de la consulta de movimientos"
          example: "2020-01-01"
        transactionEndDate:
          type: "string"
          description: "Fecha fin de la consulta de movimientos"
          example: "2020-01-30"
        transactionMinAmount:
          type: "string"
          description: "valor inicio de la consulta de movimientos (16 enteros 4 decimales)"
          maxLength: 20
          example: "5000000000"
        transactionMaxAmount:
          type: "string"
          description: "valor fin de la consulta de movimientos (16 enteros 4 decimales)"
          maxLength: 20
          example: "20000000000"
        transactionType:
          type: "string"
          description: "Tipo o naturaleza del movimiento"
          example: "DEBITO"
        transactionCheckNumber:
          type: "string"
          description: "Número de cheque"
          maxLength: 16
          example: "0000000000245358"
        transactionGroup:
          type: "string"
          description: "Grupo al que pertenece el movimiento"
          maxLength: 2
          example: "1"
        transactionDescription:
          type: "string"
          description: "Descripción del movimiento"
        officeCode:
          type: "string"
          description: "Código de la oficina donde se realizó la transacción o de la oficina dueña de la cuenta"
          maxLength: 8
          example: "2005678"
        officeDescription:
          type: "string"
          description: "Nombre de la oficina donde se realizó la transacción o de la oficina dueña de la cuenta"
          maxLength: 50
          example: ""
          
  #################################################################################
  # Scheme OFFICE INFORMATION FOR AN TRANSACTION
  #################################################################################
    officeInformation:
      type: "object"
      required:
        - code
        - name
      description: "Información de la sucursal"
      properties:
        code:
          type: "string"
          maxLength: 8
          example: "12345678"
          description: "Código de la oficina donde se realizó la transacción o de la oficina dueña de la cuenta a la que pertenece la transacción."
        name:
          type: "string"
          maxLength: 50
          description: "Nombre de la oficina donde se realizó la transacción o de la oficina dueña de la cuenta a la que pertenece la transacción."
          example: "SERVICIOS ELECTR."
          
  #################################################################################
  # Scheme RELATED TRANSFER ACCOUNT INFORMATION FOR AN TRANSACTION
  #################################################################################
    relatedTransferAccountInformation:
      type: "object"
      required:
        - type
        - number
      description: "Información de la cuenta relacionada, solo para transferencias"
      properties:
        type:
          type: "string"
          description: "Tipo de cuenta asociada al movimiento"
          example: "CUENTA_DE_AHORRO"
        number:
          type: "string"
          description: "Número de cuenta asociada al momvimiento"
          example: "01530951240"
          maxLength: 16
  #################################################################################
  # Scheme CUSTOMER INFORMATION FOR AN TRANSACTION
  #################################################################################
    customerInformation:
      type: "object"
      required:
        - name
      description: "Información del cliente dueño de la cuenta destino cuando el movimiento fue transferencia"
      properties:
        name:
          type: "string"
          description: "Nombre del cliente titular de la cuenta asociada a la transferencia"
          example: "Ramon Hoyos"
          maxLength: 100
  #################################################################################
  # Scheme MOVEMENTS INFORMATION FOR AN ACCOUNT
  #################################################################################
    movementsInformation:
      type: "object"
      required:
        - id
        - postedDate 
        - description
        - amount
        - type
      description: "Datos del Proveedor"
      properties:
        id:
          type: "string"
          maxLength: 6
          example: "8316"
          description: "código de la transacción que identifica el tipo de movimiento en depositos."
        postedDate:
          type: "string"
          description: "Fecha efectiva en la cual se hace la afectación del saldo de la cuenta, puede ser de días anteriores."
          example: "2020-03-01"
        description:
          type: "string"
          maxLength: 50
          description: "Descripción o nombre del movimiento"
          example: "Abono preautorizado donación"
        amount:
          type: "number"
          format: "float"
          maxLength: 20
          description: "Valor del movimiento"
          example: "12,400.0000"
        type:
          type: "string"
          description: "Tipo de movimiento, indica si la transacción es de naturaleza débito o crédito"
          example: "DEBITO"
        reference1:
          type: "string"
          maxLength: 50
          description: "Texto libre que coloca el consumidor al realizar los movimientos en el cual puede indicar una referencia o valor útil para el cliente. Ejemplo= número de documento de identidad, código de una factura."
          example: ""
        reference2:
          type: "string"
          maxLength: 50
          description: "Texto libre que coloca el consumidor al realizar los movimientos en el cual puede indicar una referencia o valor útil para el cliente. Ejemplo= número de documento de identidad, código de una factura."
          example: ""
        reference3:
          type: "string"
          maxLength: 50
          description: "Texto libre que coloca el consumidor al realizar los movimientos en el cual puede indicar una referencia o valor útil para el cliente. Ejemplo= número de documento de identidad, código de una factura."
          example: ""
        checkNumber:
          type: "string"
          maxLength: 16
          description: "Corresponde al número de cheque en caso tal que el movimiento haya sido CHEQUE."
          example: "NULL"

  #################################################################################
  # Scheme Status
  #################################################################################
    status:
      type: object
      description: "Estructura general de código de respuesta"
      properties:
        status:
          description: 'Codigo status petición http'
          type: string
          example: "200"
        code:
          description: 'An application-specific error code, expressed as a string value.'
          type: string
          example: "000"
        title:
          description: 'A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence of the problem, except for purposes of localization.'
          type: string
          example: TRANSACCION EXITOSA
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: TRANSACCION EXITOSA
        severity:
          description: Servity of error.
          type: string
          example: INFO
  #################################################################################
  # Scheme Error
  #################################################################################
    Error:
      type: object
      description: "Estructura general de errores"
      properties:
        status:
          description: 'Codigo status petición http'
          type: string
          example: 401
        code:
          description: 'An application-specific error code, expressed as a string value.'
          type: string
          example: 401
        title:
          description: 'A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence of the problem, except for purposes of localization.'
          type: string
          example: Lo sentimos, tenemos inconvenientes con nuestros sistemas,
            nuestro equipo se encuentra trabajando para brindarte una solución.
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Lo sentimos, tenemos inconvenientes con nuestros sistemas, nuestro equipo se encuentra trabajando
            para brindarte una solución.
        severity:
          description: Servity of error.
          type: string
          example: ERROR